export default {
	"@vocab": "http://velo.fr/",
	"@base": "http://velo.fr/lyon/", 
	"number": "@id",
	"name":"name",
	"address": null,
	"address2": null,
	"commune": null,
	"nmarrond":null,
	"bonus":null,
	"pole": null,
	"lat":{"@id":"http://www.w3.org/2003/01/geo/wgs84_pos#lat", "@type":"http://www.w3.org/2001/XMLSchema#double"},
	"lng": {"@id":"http://www.w3.org/2003/01/geo/wgs84_pos#long", "@type":"http://www.w3.org/2001/XMLSchema#double"},
	"bike_stands": {"@id":"capacity", "@type":"xsd:integer"},
	"status": null,
	"available_bike_stands":{"@id":"availableDocks", "@type":"http://www.w3.org/2001/XMLSchema#integer"},
	"available_bikes": {"@id":"availableBikes", "@type":"http://www.w3.org/2001/XMLSchema#integer"},
	"availabilitycode":null,
	"availability": null,
	"banking": null,
	"gid": null,
	"last_update": {"@id":"lastUpdated", "@type":"http://www.w3.org/2001/XMLSchema#dateTime"},
	"last_update_fme": null,
	"code_insee": null,
	"langue":null, "etat":null, "nature": null, "titre": null, "description": null, "startdate": null, "enddate": null,
	"geometry": null,
	"properties": "@nest",
	"type": null
}